version: '3'

volumes:
  express_node_modules:
  postgres_db:

services:
  express:
    restart: always
    build:
      context: .
      dockerfile: ./compose/express/Dockerfile
    command: /start.sh
    depends_on:
      - db
      - redis
    ports:
      - "6781:6781"
    volumes:
      - .:/app/
      - express_node_modules:/app/node_modules
  db:
    image: postgres:10.3
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_DB:postgres
  redis:
    restart: always
    image: redis:5.0-alpine
    container_name: "my_redis"
