module.exports = {
  //selected feed
  ADD_FEED_LIST: "ADD_FEED_LIST",
  SET_CURRENT_FEED: "SET_CURRENT_FEED",
  FEED_PENDING: "FEED_PENDING",
  SET_SERVER_STATE: "SET_SERVER_STATE",
  REFRESH_HASH_FEED: " REFRESH_HASH_FEED",
  DELETE_CURRENT_FEED: "DELETE_CURRENT_FEED",

  //hashtags
  ADD_TAG_LIST: "ADD_TAG_LIST",
  ADD_TAG: "ADD_TAG",
  HASH_LIST_PENDING: "HASH_LIST_PENDING",
  SEARCH_PENDING: "SEARCH_PENDING",
  REFRESH_TAG: "REFRESH_TAG",
  DELETE_TAG: "DELETE_TAG",
  ADD_TAG_CHECKED_LIST: "ADD_TAG_CHECKED_LIST",
  SET_BACKEND_WORK: "SET_BACKEND_WORK",
  OK: "OK"
};
