module.exports = {
  //selected feed
  ADD_FEED_LIST: "ADD_FEED_LIST",
  SET_CURRENT_FEED: "SET_CURRENT_FEED",
  FEED_PENDING: "FEED_PENDING",

  //hashtags
  ADD_TAG_LIST: "ADD_TAG_LIST",
  ADD_TAG: "ADD_TAG",
  HASH_LIST_PENDING: "HASH_LIST_PENDING",
  SEARCH_PENDING: "SEARCH_PENDING",
  REFRESH_TAG: "REFRESH_TAG",
  DELETE_TAG: "DELETE_TAG",
  OK: "OK"
};
